version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  cache:
    layerinfo: redis
  s3:
    accesskey: fworkmini0
    secretkey: FworkMini0
    region: fwork-staging
    regionendpoint: storage.fpt.work
    encrypt: False
    bucket: fwork-harbor
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
  redirect:
    disable: true
redis:
  addr: redis:6379
  readtimeout: 10s
  writetimeout: 10s
  dialtimeout: 10s
  password: 
  db: 1
http:
  addr: :5000
  secret: placeholder
  debug:
    addr: localhost:5001
auth:
  htpasswd:
    realm: harbor-registry-basic-realm
    path: /etc/registry/passwd
validation:
  disabled: true
compatibility:
  schema1:
    enabled: true
